spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://140.143.163.212:3306/financial?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 5cebe5f8222b041849cdc0ff776f38b2
#    url: jdbc:h2:mem:manager;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
#  activemq:
#    broker-url: tcp://10.5.16.14:61616
#  jms:
#    pub-sub-domain: true
server:
  servlet:
    context-path: /manager
  port: 8081